In [12]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import joblib

In [13]:
df = pd.read_csv("../data/processed/cleaned_comments.csv")

df.head()

,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,cleaned_text,is_toxic,cleaned_length
0,Explanation\r\nWhy the edits made under my use...,0,0,0,0,0,0,explanation edits made username hardcore metal...,0,168
1,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,daww match background colour seemingly stuck t...,0,68
2,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,hey man really trying edit war guy constantly ...,0,141
3,"""\r\nMore\r\nI can't make any real suggestions...",0,0,0,0,0,0,cant make real suggestion improvement wondered...,0,362
4,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,sir hero chance remember page thats,0,35

In [14]:
X = df["cleaned_text"]
y = df["is_toxic"]

In [15]:
label_columns = ["toxic", "severe_toxic", "obscene", 
                 "threat", "insult", "identity_hate"]

X = df["cleaned_text"]
y = df[label_columns]

In [16]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),   # unigrams + bigrams
    min_df=2,
    max_df=0.9
)

In [17]:
X_tfidf = vectorizer.fit_transform(X)

print("TF-IDF Shape:", X_tfidf.shape)

TF-IDF Shape: (159483, 10000)

In [18]:
feature_names = vectorizer.get_feature_names_out()

print("Total Features:", len(feature_names))
print("Sample Features:", feature_names[:20])

Total Features: 10000
Sample Features: ['aaron' 'abandoned' 'abbreviation' 'abc' 'abide' 'ability' 'able'
 'able edit' 'able find' 'able get' 'abortion' 'abraham' 'abroad'
 'absence' 'absent' 'absolute' 'absolutely' 'absolutely nothing'
 'abstract' 'absurd']

In [19]:
pd.DataFrame(
    X_tfidf[:5].toarray(),
    columns=feature_names
).iloc[:, :20]

,aaron,abandoned,abbreviation,abc,abide,ability,able,able edit,able find,able get,abortion,abraham,abroad,absence,absent,absolute,absolutely,absolutely nothing,abstract,absurd
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.2, random_state=42
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (127586, 10000)
Test shape: (31897, 10000)

In [21]:
joblib.dump(vectorizer, "../models/vectorizer.pkl")

print("✅ Vectorizer saved successfully")

✅ Vectorizer saved successfully

In [22]:
joblib.dump(X_train, "../models/X_train.pkl")
joblib.dump(X_test, "../models/X_test.pkl")
joblib.dump(y_train, "../models/y_train.pkl")
joblib.dump(y_test, "../models/y_test.pkl")

print("✅ Train/Test data saved")

✅ Train/Test data saved